In [33]:
import gym
import gym_bart
import sys
import pickle
sys.path.append('..')
from ppo.envs import *
from stable_baselines3.common.vec_env import (DummyVecEnv, SubprocVecEnv,
                                              VecEnvWrapper)
from stable_baselines3.common.vec_env.vec_normalize import VecNormalize
import torch


In [2]:
envs = make_vec_env('BartEnv-v0', n_envs=4, env_kwargs={"colors_used": 3}, seed=3)
envs = VecNormalize(envs)
a = torch.ones((4, 1), dtype=torch.int)
b = torch.zeros((4, 1), dtype=torch.int)

In [3]:
envs.reset()

array([[ 1.0000000e+00,  0.0000000e+00, -1.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  1.7671926e-05,  0.0000000e+00],
       [ 1.0000000e+00,  0.0000000e+00, -1.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  1.7671926e-05,  0.0000000e+00],
       [-1.0000000e+00,  0.0000000e+00,  1.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  1.7671926e-05,  0.0000000e+00],
       [-1.0000000e+00,  0.0000000e+00,  1.0000000e+00,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  1.7671926e-05,  0.0000000e+00]],
      dtype=float32)

In [20]:
obs, rew, done, infos = envs.step(a)

In [32]:
obs, rew, done, infos = envs.step(a)
infos

[{'current_color': 'orange',
  'last_size': 0.2363977103065878,
  'popped': False,
  'TimeLimit.truncated': False},
 {'current_color': 'orange',
  'last_size': 0.7740089997487066,
  'popped': True,
  'episode': {'r': 0.0, 'l': 16, 't': 73.345547},
  'TimeLimit.truncated': False,
  'terminal_observation': array([-0.26908115, -0.47314665,  0.5379447 ,  0.        ,  0.        ,
         -1.5864427 , -0.19670238,  0.19649458], dtype=float32)},
 {'current_color': 'yellow',
  'last_size': 0.04069163348861189,
  'popped': False,
  'TimeLimit.truncated': False},
 {'current_color': 'yellow',
  'last_size': 0.13722261300851912,
  'popped': False,
  'TimeLimit.truncated': False}]

In [75]:
rew.shape

(4,)

In [60]:
from ppo.storage import RolloutStorageAux

In [80]:
storage = RolloutStorageAux(64, 4, envs.observation_space.shape,
                            envs.action_space, 0)

In [81]:
storage.step

0

In [82]:
storage.rewards.shape

torch.Size([64, 4, 1])

In [83]:
rew = torch.tensor(rew, dtype=torch.float).reshape(-1, 1)
storage.rewards[storage.step].copy_(rew)

C:\Users\14and\AppData\Local\Temp\ipykernel_29752\3357033629.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  rew = torch.tensor(rew, dtype=torch.float).reshape(-1, 1)


tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [7]:
torch.load('../saved_models/basics/1color_mlp_bs128_t0.pt')

[Policy(
   (base): FlexBaseAux(
     (critic0): Sequential(
       (0): Linear(in_features=8, out_features=64, bias=True)
       (1): Tanh()
     )
     (actor0): Sequential(
       (0): Linear(in_features=8, out_features=64, bias=True)
       (1): Tanh()
     )
     (critic1): Sequential(
       (0): Linear(in_features=64, out_features=64, bias=True)
       (1): Tanh()
     )
     (actor1): Sequential(
       (0): Linear(in_features=64, out_features=64, bias=True)
       (1): Tanh()
     )
     (critic_head): Linear(in_features=64, out_features=1, bias=True)
   )
   (dist): Categorical(
     (linear): Linear(in_features=64, out_features=2, bias=True)
   )
 ),
 (<stable_baselines3.common.running_mean_std.RunningMeanStd at 0x1a4f2df48b0>,
  <stable_baselines3.common.running_mean_std.RunningMeanStd at 0x1a4f2df4970>)]

In [8]:
env = gym.make('BartEnv-v0')

In [11]:
env.reset()

(array([0., 1., 0., 0., 0., 0., 1., 0.], dtype=float32), {})

In [12]:
%%timeit
env.get_observation()

c:\Users\14and\anaconda3\envs\bart\lib\site-packages\gymnasium\core.py:311: UserWarning: WARN: env.get_observation to get variables from other wrappers is deprecated and will be removed in v1.0, to get this variable you can do `env.unwrapped.get_observation` for environment variables or `env.get_wrapper_attr('get_observation')` that will search the reminding wrappers.
  logger.warn(


6.35 µs ± 79.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [13]:
%%timeit
env.step(0)

1.74 µs ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
envs = make_vec_env('BartEnv-v0', n_envs=4, env_kwargs={"colors_used": 3}, seed=3)
# envs = VecNormalize(envs)
a = torch.ones((4, 1), dtype=torch.int)
b = torch.zeros((4, 1), dtype=torch.int)
envs.reset()

array([[ 0.99997497,  0.        , -0.99992496,  0.        ,  0.        ,
         0.        ,  0.00353516,  0.        ],
       [ 0.99997497,  0.        , -0.99992496,  0.        ,  0.        ,
         0.        ,  0.00353516,  0.        ],
       [-0.99992496,  0.        ,  0.99997497,  0.        ,  0.        ,
         0.        ,  0.00353516,  0.        ],
       [-0.99992496,  0.        ,  0.99997497,  0.        ,  0.        ,
         0.        ,  0.00353516,  0.        ]], dtype=float32)

In [20]:
%%timeit
envs.step(b)

483 µs ± 13.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [3]:
from stable_baselines3.common.env_util import make_vec_env

In [31]:
envs = make_vec_env(env_id='BartEnv-v0', n_envs=4,)
b = torch.zeros((4, 1), dtype=torch.int)
a = torch.ones((4, 1), dtype=torch.int)


In [58]:
class SimpleVecEnv():
    def __init__(self, env_id='BartEnv-v0', num_envs=1, env_kwargs={},
                 ):
        self.num_envs = num_envs
        self.envs = [gym.make(env_id, **env_kwargs) for i in range(num_envs)]

        assert len(self.envs[0].observation_space.shape) == 1
        self.obs = np.zeros((self.num_envs, self.envs[0].observation_space.shape[0]), dtype=np.float32)
        self.rews = np.zeros((self.num_envs), dtype=np.float32)
        self.terms = np.full((self.num_envs), False)
        self.infos = [{}]*self.num_envs
        self.lens = np.zeros((self.num_envs))
        self.rets = np.zeros((self.num_envs))
    
    def reset(self):
        for i in range(self.num_envs):
            o, info = self.envs[i].reset()
            self.obs[i] = o
        return self.obs.copy()

    def step(self, actions):
        assert len(actions) == self.num_envs
        
        self.infos = []
        for i in range(self.num_envs):
            o, r, term, trunc, info = self.envs[i].step(actions[i])
            self.lens[i] += 1
            self.rets[i] += r
            self.obs[i] = o
            self.terms[i] = term
            
            self.infos.append(info)
            if term:
                self.infos[i]['episode'] = {'r': self.rets[i], 'l': self.lens[i]}
                self.infos[i]['terminal_observation'] = o
                o, _ = self.envs[i].reset()
                self.obs[i] = o
        
        return self.obs, self.rews, self.terms, self.infos
            

In [59]:
envs2 = SimpleVecEnv(num_envs=4)

In [38]:
from read_experiments import load_exp_df, print_runs
df = load_exp_df('basics/3color_test', trial_num=0)

In [40]:
df['metric'].unique()

array(['charts/episodic_return', 'charts/episodic_length',
       'charts/episodic_bonus_rewards', 'bart/color', 'bart/size',
       'bart/popped', 'charts/learning_rate', 'losses/value_loss',
       'losses/policy_loss', 'losses/auxiliary_loss', 'losses/entropy',
       'losses/approx_kl', 'losses/clipfrac', 'charts/SPS'], dtype=object)

In [42]:
df[df['metric'] == 'bart/popped']['value'].unique()

array([0., 1.])