In [1]:
import gym
import gym_bart
import sys
import pickle
sys.path.append('..')
from ppo.envs import *
from stable_baselines3.common.vec_env import (DummyVecEnv, SubprocVecEnv,
                                              VecEnvWrapper)
from stable_baselines3.common.vec_env.vec_normalize import VecNormalize


In [15]:
envs = make_vec_env('BartEnv-v0', n_envs=4, env_kwargs={"colors_used": 3}, seed=3)
envs = VecNormalize(envs)

In [21]:
envs.reset()

array([[ 9.9997282e-01, -1.5808305e-03, -9.9996030e-01,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  2.0828830e-08,  0.0000000e+00],
       [ 9.9997282e-01, -1.5808305e-03, -9.9996030e-01,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  2.0828830e-08,  0.0000000e+00],
       [-9.9994367e-01, -1.5808305e-03,  9.9996448e-01,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  2.0828830e-08,  0.0000000e+00],
       [-9.9994367e-01, -1.5808305e-03,  9.9996448e-01,  0.0000000e+00,
         0.0000000e+00,  0.0000000e+00,  2.0828830e-08,  0.0000000e+00]],
      dtype=float32)

In [25]:
envs.obs_rms.count

4.0001

In [27]:
torch.save([(envs.obs_rms, envs.ret_rms)], 'test')

In [30]:
envs.observation_space.shape

(8,)

In [55]:
a = torch.ones((4, 1), dtype=torch.int)
b = torch.zeros((4, 1), dtype=torch.int)

In [56]:
envs.step(b)

(array([[-0.291109  ,  4.5091653 , -2.645729  ,  0.        ,  0.        ,
         -1.2286915 ,  2.1950135 , -2.1950135 ],
        [ 3.4350767 , -0.22176445, -2.645729  ,  0.        ,  0.        ,
         -1.2286915 ,  2.1950135 , -2.1950135 ],
        [-0.291109  , -0.22176445,  0.37796354,  0.        ,  0.        ,
         -1.2286915 ,  2.1950135 , -2.1950135 ],
        [-0.291109  ,  4.5091653 , -2.645729  ,  0.        ,  0.        ,
         -1.2286915 ,  2.1950135 , -2.1950135 ]], dtype=float32),
 array([4.303236 , 3.7404952, 5.527695 , 0.       ], dtype=float32),
 array([ True,  True,  True,  True]),
 [{'episode': {'r': 0.595174, 'l': 14, 't': 800.283625},
   'TimeLimit.truncated': False,
   'terminal_observation': array([-0.291109  , -0.22176445,  0.37796354,  0.        ,  0.        ,
           1.4008367 ,  2.1950135 , -2.1950135 ], dtype=float32)},
  {'episode': {'r': 0.517342, 'l': 12, 't': 800.282473},
   'TimeLimit.truncated': False,
   'terminal_observation': array([-0.2

In [57]:
a

tensor([[1],
        [1],
        [1],
        [1]], dtype=torch.int32)

In [59]:
a[:] = np.zeros((4, 1))

TypeError: can't assign a numpy.ndarray to a torch.IntTensor

In [53]:
envs.save

<bound method VecNormalize.save of <stable_baselines3.common.vec_env.vec_normalize.VecNormalize object at 0x000001C8999B9F10>>

In [12]:
envs.save('test')

In [13]:
file = pickle.load(open('test', 'rb'))

In [12]:
mean = envs.obs_rms.mean

In [18]:
envs.obs_rms.mean = mean

In [20]:
envs.obs_rms.mean

array([0.20833247, 0.33333194, 0.45833142, 0.        , 0.        ,
       0.        , 0.99999583, 0.        ])

In [5]:
import torch

In [4]:
action = torch.tensor([[1]])

In [10]:
envs.reset()

tensor([[0.0000, 0.0071, 0.0000, 0.0000, 0.0000, 0.0000, 0.0071, 0.0000]])

In [5]:
envs.step(action)

(array([[0.       , 1.       , 0.       , 0.       , 0.       , 0.0447975,
         0.       , 1.       ]], dtype=float32),
 array([0.], dtype=float32),
 array([False]),
 [{'TimeLimit.truncated': False}])

In [16]:
env = gym.make('BartEnv-v0', hold_to_inflate=True)

In [18]:
from stable_baselines3.common.env_util import make_vec_env

In [20]:
from stable_baselines3.common.vec_env.patch_gym import _patch_env

In [19]:
make_vec_env("BartEnv-v0")

NameNotFound: Environment `BartEnv` doesn't exist.